//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JarmuKolcsonzo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jarmu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public jarmu()
        {
            this.rendeles = new HashSet<rendeles>();
        }
    
        public int id { get; set; }
        public string rendszam { get; set; }
        public int tipus_id { get; set; }
        public int dij { get; set; }
        public bool elerheto { get; set; }
        public Nullable<System.DateTime> szerviz_datum { get; set; }
    
        public virtual jarmu_tipus jarmu_tipus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rendeles> rendeles { get; set; }
    }
}
