//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JarmuKolcsonzo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jarmu_tipus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public jarmu_tipus()
        {
            this.jarmu = new HashSet<jarmu>();
        }
    
        public int id { get; set; }
        public string megnevezes { get; set; }
        public int ferohely { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<jarmu> jarmu { get; set; }
    }
}
